Level: 1

Title: "Sources"

Abstract: "In this research aid you find information on where you can find relevant source material for your (provenance) research and how to critically approach the information that you found."

RelatedAides: 
  - "Doing research":
        link: "niveau1/English/DoingResearch.yml"
        rel_type: "see also"
  - "Civil servants in colonised territories":
        link: "niveau2/English/CivilServants.yml"
        rel_type: "see also"
  - "The trade in objects from a colonial context":
        link: "niveau2/English/Trade.yml"
        rel_type: "see also"
  - "Army and navy personnel in colonised territories":
        link: "niveau2/English/MilitaryAndNavy.yml"
        rel_type: "see also"
  - "Christian missionaries in colonised territories":
        link: "niveau2/English/ChristianMission.yml"
        rel_type: "see also"
  - "Scientific research in colonised territories":
        link: "niveau2/English/Science.yml"
        rel_type: "see also"
  - "Wereldmuseum Leiden":
        link: "niveau3/English/WMLeiden.yml"
        rel_type: "see also"
  - "Royal Netherlands Institute of Southeast Asian and Caribbean Studies (KITLV)":
        link: "niveau3/English/KITLV.yml"
        rel_type: "see also"
  - "Naturalis Biodiversity Center":
        link: "niveau3/English/Naturalis.yml"
        rel_type: "see also"
  - "Wereldmuseum Amsterdam":
        link: "niveau3/English/WMAmsterdam.yml"
        rel_type: "see also"
  - "Wereldmuseum Rotterdam":
        link: "niveau3/English/WMRotterdam.yml"
        rel_type: "see also"
  - "Museum Bronbeek":
        link: "niveau3/English/Bronbeek.yml"
        rel_type: "see also"
  - "Rijksmuseum Amsterdam":
        link: "niveau3/English/RijksmuseumAmsterdam.yml"
        rel_type: "see also"
  - "Rijksmuseum van Oudheden":
        link: "niveau3/English/RMO.yml"
        rel_type: "see also"

Main-text:
  content: |
    ## Critical handling of sources
    
    When researching the provenance of objects from colonial contexts it is important to keep the following issues in mind:
    - the knowledge and expertise of people from the countries or communities of origin are important sources for the history of the objects;
    - colonial sources reflect the ideas and power relations of the time. 
    
    Colonial sources often use concealing language. For example, objects were 'found' or 'taken' and individuals in colonised territories were often described in a derogatory or paternalistic way. Regardless of the case, colonial sources were written from a perspective that justified colonial rule and critical handling is needed to avoid  reproducing the colonial power relations of the time. Therefore, be aware of the tone in such sources and take this into account when carrying out your own research. For example, historical language used in sources will require contextualisation, and this includes recognition of their colonial perspective. It is also important to involve communities of origin as early in the research as possible.
    
    The Wereldmuseum publication _[Words Matter](https://amsterdam.wereldmuseum.nl/sites/default/files/2021-04/words_matter.pdf.pdf)_ provides tips for dealing with colonial terminology.
      
    ## Search terms
    
    When conducting provenance research into colonial collections you will need to use different search terms from the modern terminology we use today. This includes place names, which were often changed after decolonisation. For example, Batavia became [Jakarta](https://sws.geonames.org/1642911/jakarta.html) and Leopoldville became [Kinshasa](https://sws.geonames.org/2314302/kinshasa.html). Where place names remained the same, they are often spelled differently today compared to the colonial period (think for example of [Soerabaja/Surabaya](https://sws.geonames.org/1625822/surabaya.html) and [Tjirebon/Cirebon](https://sws.geonames.org/1646170/cirebon.html)).
    
    Terminology used to refer to objects has also changed – for example, a 'baadje' is nowadays called a jacket. In the Dutch East Indies, terms derived from Indonesian were also in use, such as 'rampokken' and 'rampassen' as synonyms for ‘plundering’. Non-Dutch names were spelled in different ways, even in colonial times. Dutch nationals were often referred to only by their last name and initials. For this reason, always try to find out which names and terms were used, and try entering different variants when using search engines.
    
    ## Where to find sources?
    
    **Personal archives and egodocuments**
    
    Personal archives such as diaries, memoirs and letters are often crucial in provenance research into objects from colonial contexts. Personal archives may also contain copies of reports and records made in a professional capacity. This is important because significant portions of colonial government archives have not been preserved. 
   
    Such private collections can be found in numerous archives in the Netherlands. It is therefore advisable to begin your search at [archieven.nl](https://www.archieven.nl/). However, not all archival institutions can be found here, so it will often be necessary to extend your search beyond this website. Many Dutch nationals who were active in colonial administration, the military or science deposited their personal archives at the [Royal Netherlands Institute of Southeast Asian and Caribbean Studies (KITLV)](https://app.colonialcollections.nl/en/research-aids/https%3A%2F%2Fn2t%252Enet%2Fark%3A%2F27023%2F62191a1bbed9b315db786f2037417b4f). These archives are now part of the [Leiden University Libraries](https://digitalcollections.universiteitleiden.nl). Sometimes archive documents are still privately held by families, organisations or companies.
    
    The [National Archives of the Netherlands](https://www.nationaalarchief.nl) website provides an online search function for the personnel files (service registers) of colonial civil servants, military and naval personnel. This makes it possible to find out when and where they were stationed, and for what actions they were awarded honours and distinctions.
  
    **Archives of institutions and governments**
    
    These include archives of institutions that have had custody of the object, for instance museums or dealers in art and ethnographic objects. Archives of some (former) museum collections and institutions are deposited in national, provincial or municipal archives. Keep in mind that in addition to these deposited archives, archival materials are often also held by the institution itself.
    
    In terms of government archives, the archives of the Ministry of Colonies, the Ministries of War and Navy, and the Ministry of the Interior are of particular importance; these are housed in the National Archives of the Netherlands. Large sections of the archives of the Dutch East India Company (VOC) are also held here, including the personal archives of governors and local records of trading posts. Significant parts of these archives have now been digitalised. The National Archives of the Netherlands offers several [research aids](https://www.nationaalarchief.nl/onderzoeken/zoekhulpen) to help users find their way around the archives. The research aid [De koloniale staat 1854-1942](https://www.nationaalarchief.nl/onderzoeken/archief/2.14.97/invnr/10ED/file/Koloniale%20staat.pdf) (Dutch only) contains detailed explanations of the archives relating to the Dutch East Indies and the various official departments.
 
    **Newspapers**
    
    In the colonial era, much more was reported in the newspapers than today. For example, they carried extensive reports of military actions, and transfers of military and colonial officials were announced through the papers. Donations of items to museums and other institutions were also often reported. 
   
    An important resource for provenance research is the website [www.delpher.nl](https://www.delpher.nl), which enables historical (Dutch) newspapers, books, magazines and radio bulletins to be searched online. It also includes Dutch-language newspapers from the former colonies, which contain information about private individuals, maritime passengers and specific events. The Drents Archief produced a video with tips for conducting searches in [Delpher](https://youtu.be/PfXY9aQC7F4). 
    
    **Books and magazines**

    Dutch books and magazines from the colonial era often contain extensive travel reports and accounts of events of various kinds. As such, these publications are a rich source for provenance research, albeit with a colonial gaze. Additionally, objects may be featured in exhibition catalogues and other publications, many of which have now been digitalised. These can be searched on websites including: 
    - [Delpher](https://www.delpher.nl)
    - [Digital Collections of Leiden University](https://digitalcollections.universiteitleiden.nl)
    - [Google Books](https://books.google.nl)
    
    **Image material, maps and plans**
    
    Photographs can provide a picture of how objects were used in the regions of origin. They can also contain information about sites, excavations, museum displays or domestic interiors, which can be used to identify objects. Other visual materials, such as drawings and paintings, can also be useful in this regard.
   
    The most extensive image databases in the Netherlands with material on the areas colonised by European powers are those of [Leiden University Library](https://digitalcollections.universiteitleiden.nl/imagecollection-kitlv) and the [Wereldmuseum](https://collectie.wereldculturen.nl) along with the image collections of the [National Archives](https://www.nationaalarchief.nl/onderzoeken/fotos) and the [Rijksmuseum](https://www.rijksmuseum.nl/nl/rijksstudio). The [National Museum of Photography](https://www.nederlandsfotomuseum.nl/) owns the image library of the Wereldmuseum in Rotterdam.
    
    Maps and plans from the colonial era can help locate the place of origin and can be found in the collections of the [National Archives](https://www.nationaalarchief.nl/onderzoeken/kaarten-en-tekeningen/navigatie-en-overzeese-expansie) and [Leiden University Library](https://www.library.universiteitleiden.nl/special-collections/collections/maps-and-atlases).
   
    **Communities in the regions of origin**
    
    Information about the object's history can almost always be found in its area of origin. This includes written and oral sources as well as information about the function and meaning of the object. Such information is an important source for understanding the provenance of an object and the circumstances under which it came to the Netherlands.
   
    **Experts in the Netherlands and countries of origin**
    
    Sometimes information about an object is unwritten, in which case experts, both in the Netherlands and in the countries of origin, can be an important source of information. They may include (former) museum staff and scientific experts but also dealers, collectors, artisans and artists. Communities often still have knowledge about how objects were manufactured and used.

    **Archives outside the Netherlands**
    
    A guiding principle in the archival world is that archives are kept where they were formed. For this reason, many archives related to Dutch colonial collections are located in the former colonies. Archival institutions containing such material include the [National Archives of Suriname](https://nationaalarchief.sr/), [Arsip Nasional Republik Indonesia](https://www.anri.go.id), the [National Archives of Sri Lanka](https://www.archives.gov.lk) and the [National Archives of Curaçao](https://www.nationaalarchief.cw/). Various archives in Indonesia can be accessed via the [JIKN](https://jikn.anri.go.id/) portal.
    
    An example is the archive of the Bataviaasch Genootschap van Kunsten en Wetenschappen (Royal Batavian Society of Arts and Sciences), which is held at the Arsip Nasional in Jakarta, the city where the institution was based. And yet many archive documents concerning the Bataviaasch Genootschap can also be found in the Netherlands, for example in personal archives of individuals who were involved with the Society. 
    
    Some collectors and organisations were active in several European countries, which means that relevant information may also be located in other European countries. In Germany such information can be found through the portals [Proveana](https://www.proveana.de/en/start) and [Archivführer zur deutschen Kolonialgeschichte](https://archivfuehrer-kolonialzeit.de) and the database [Sammlungsgut aus kolonialen Kontexten](https://ccc.deutsche-digitale-bibliothek.de). The French portal [AGORHA](https://agorha.inha.fr) contains information on collectors, dealers and collections in the fields of archaeology and art history, including Asian art.
  content-type: text/markdown

editing_metadata:
  - date: 2024-05-01
    applies_to: 
    author: wiebe reints
    role: original_author
    editing_notes: metadata added on 2025-06-02. from now, mayor changes to the file need to be logged here. 
  - date: 2025-03-12
    applies_to: Maint-text
    author: abacus
    role: translator
    editing_notes: abacus translations processed by wiebe reints 